### ISSUE TITLE
Use `setrounding` globally when package is loaded

### ISSUE THREAD

**Issue by dpsanders** [lairez/ExactPredicates.jl#1]
Although using `setrounding` globally is a bad idea, I think you should at least just set it globally once when `ExactPredicates` is loaded, rather than including it in the generated code.

cc @jeffbezanson

**Comment by lairez** [comment]
Very sorry for the late answer. What is the problem with calling `setrounding` multiple times? Do you expect the overhead to be really large?  

That being said it looks like https://github.com/JuliaIntervals/IntervalArithmetic.jl/issues/302 is resolved (is it?). That was the only motivation for using `setrounding(Interval, :slow)`, so I will just remove that

**Comment by dpsanders** [comment]
Calling `setrounding` redefines all the functions in the package, and is hence very slow.
It is meant to only be called once.

Yes, that issue has since been fixed; sorry for not pointing that out earlier.

**Comment by lairez** [comment]
Great!
