### ISSUE TITLE
Incorrect value from `rotation`

### ISSUE THREAD

**Issue by DanielVandH** [lairez/ExactPredicates.jl#13]
Found this when running the tests:

```julia
using ExactPredicates, Random
Random.seed!(521);
angles = 3 * pi * 2 * rand(30); sort!(angles);
pts = [exp(im * α) for α in angles];
```
```julia
julia> rotation(pts)
2
```

I'm not sure exactly what the issue is here, but it should be 3? That's what you're testing for in the tests.

**Comment by lairez** [comment]
The value is actually correct because `angle[17]-angle[16]` is larger than π.

![plot](https://user-images.githubusercontent.com/7419568/236621014-ad84bc39-f708-40fd-ade8-f11fa260e3cd.png)

**Comment by lairez** [comment]
But indeed, the test needs a fix, I thought that the probability of that happening were small enough...
