### ISSUE TITLE
Possible compatibility constraint issue with old versions of StaticArrays

### ISSUE THREAD

**Issue by pedrosecchi67** [lairez/ExactPredicates.jl#14]
Hi!

I've recently faced this issue:

[https://github.com/DanielVandH/DelaunayTriangulation.jl/issues/58](https://github.com/DanielVandH/DelaunayTriangulation.jl/issues/58)

Which I believe was due to the fact that ExactPredicates does not sufficiently constrain old versions of StaticArrays. I'd appreciate it if the compat entries were checked.

**Comment by lairez** [comment]
I do not see how I could help. ExactPredicates only depend on the last version of StaticArraysCore. In your case, some other package is restricting StaticArrays to a very old version. This is where your problem is. Or maybe you have another solution in mind?

**Comment by lairez** [comment]
Without further input, I close
