### ISSUE TITLE
Better error messages for non-Float64

### ISSUE THREAD

**Issue by DanielVandH** [lairez/ExactPredicates.jl#15]
Currently, if someone uses a non-Float64 type, they get a stackoverflow, e.g.:

```julia
julia> p, q, r = (0.5f0, 0.30f0), (0.8f0, 0.19f0), (0.5f0, 0.1f0)
((0.5f0, 0.3f0), (0.8f0, 0.19f0), (0.5f0, 0.1f0))

julia> orient(p, q, r)
ERROR: StackOverflowError:
Stacktrace:
 [1] orient(u::Tuple{Float32, Float32}, v::Tuple{Float32, Float32}, w::Tuple{Float32, Float32}) (repeats 79984 times)
   @ ExactPredicates C:\Users\User\.julia\packages\ExactPredicates\GSx4w\src\Codegen.jl:422

julia> p, q, r = (5, 3), (10, 5), (17, 3)
((5, 3), (10, 5), (17, 3))

julia> orient(p, q, r)
ERROR: StackOverflowError:
Stacktrace:
 [1] orient(u::Tuple{Int64, Int64}, v::Tuple{Int64, Int64}, w::Tuple{Int64, Int64}) (repeats 79984 times)
   @ ExactPredicates C:\Users\User\.julia\packages\ExactPredicates\GSx4w\src\Codegen.jl:422
```

I wonder if it would be worth changing these error messages to be clearer, e.g. just telling the user that only Float64 coordinates are supported? (Though maybe that last one should just convert to Float64 automatically, actually.) 

I thought changing `coord` to identify these situations would be sufficient, but that won't work for custom types. Would it be sufficient to change the part here:

https://github.com/lairez/ExactPredicates.jl/blob/a1b984693f3a48176695d0a27af6075df0f825d3/src/Codegen.jl#L382-L397

to somehow check the type after pushing into `tupleconv`? Not sure the best approach, but it seems worth thinking about anyway.

**Comment by lairez** [comment]
I agree that this behavior is not nice. We should probably define the predicates with explicit typing `NTuple{2, Float64}` or `NTuple{3, Float64}` and have a catch-all function that calls `coord`, like `orient(p, q, r) = _orient(coord(p), coord(q), coord(r))`. So there will be a "no method matching" error if `coord` does not output the appropriate type. What do you think ?

**Comment by DanielVandH** [comment]
Good idea - I think that would be the best approach. I'll submit a PR for that soon.

**Comment by lairez** [comment]
I'll do it (it may be more tricky than it looks).
