### ISSUE TITLE
Move to JuliaGeometry?

### ISSUE THREAD

**Issue by juliohm** [lairez/ExactPredicates.jl#16]
Maybe worth moving this package to JuliaGeometry for greater visibility? :)

Let me know if you are not a JuliaGeometry member yet and I can add you there.

**Comment by lairez** [comment]
Maybe at some point, but for the moment JuliaGeometry already has a package for predicates. Two packages for the same thing under the same umbrella would bring a lot of confusion.

**Comment by juliohm** [comment]
You will see that a lot of packages in JuliaGeometry are dead projects. Your package seems well-documented and organized, I would simply move it there to get more traction from other potential collaborators. We already cite it in Meshes.jl docs thanks to @DanielVandH : https://juliageometry.github.io/MeshesDocs/dev/predicates.html

**Comment by lairez** [comment]
Hmm... Not so engaging ;) Let's talk again about it when JuliaGeometry will have more solid motivations.
