### ISSUE TITLE
Consider renaming the `coords` trait to `coordinates`

### ISSUE THREAD

**Issue by juliohm** [lairez/ExactPredicates.jl#17]
If you adopt `coordinates` as the trait to extract the tuple (or SVector) from the Point type, this package will work out of the box in conjunction with Meshes.jl.

We adopt more explicit names over there to avoid ambiguity.

**Comment by lairez** [comment]
The renaming will probably not be enough, because there will still be `Meshes.coordinates` and `ExactPredicates.coordinates`. So I think this is not worth the breaking change.
