### ISSUE TITLE
Supporting Float32

### ISSUE THREAD

**Issue by DanielVandH** [lairez/ExactPredicates.jl#23]
Would it be very difficult to change the code to allow for single precision arithmetic? Looking at the referenced papers, it seems possible. Are there any hard-coded numbers in the Codegen that explicitly requires Float64 to make sense, other than e.g. calls like `::Float64`, `ret = (deg = Dict(), groups = Dict(), bound = Inf, error = 0.0)` (which would require `Inf` to become `typemax(T)`, where `T` is the number type of the `Formula`, and `0.0` to be `zero(T)`), and `Base.exponent_mask(Float64)`?

If you think it might not be too hard, I'm thinking of looking into doing it at some point since I need to understand some of these methods a bit more. I'll hold off otherwise.

**Comment by lairez** [comment]
No nothing specific to Float64, you will not have bad surprises. I will merge if you PR. But bear in mind that there is little incentive to support Float32: it may end up being slower in some use cases (because the fast path will be coarser, rejecting more inputs), and people caring about numerical robustness use Float64 anyway.

**Comment by DanielVandH** [comment]
I agree that there's little to gain from supporting `Float32`. I'm mostly just trying to get my head around some of these methods, so implementing `Float32` seems like a good way to learn / check my understanding of the relevant papers. Perhaps if I do implement it, I will add a clear warning about `Float32` anyway. I'll see how implementing it goes, it might end up not being worth the technical debt to have in the package.


I'm also thinking about implementing the method from [Shewchuk](https://www.cs.cmu.edu/~quake/robust.html) for computing the `orient` predicate's associated determinant (at the very least anyway), since not being able to compute triangle areas (which uses the `orient` determinant) robustly turns out to be a real headache. Would you welcome having that in this package (otherwise I will keep it in DelaunayTriangulation.jl probably)? Not as a replacement for the `orient` predicate already here, but just as a separate function that returns a value.

**Comment by lairez** [comment]
Concerning the “robust” computation of area, it is a discussion similar to the one we had in #9. I am unable to give a meaning to this. Shewchuk guarantees the sign of the result, but does it guarantees more than that? Also, I don't know if underflows and overflows are handled.

**Comment by DanielVandH** [comment]
It is indeed mostly for the sign, but the adaptivity of the method helps to give better control over the errors. It doesn't just stop once the sign has been determined. It does not handle underflow/overflow unfortunately.

As an example of the need, a triangle's circumcenter takes has $x$-coordinates `dx = cx - (some determinant) / [2orient(a, b, c)]` and similarly for its $y$-coordinate, with `2orient(a, b, c) = 4area(a, b, c)`. Without any control over the error in `area`, this is hard to compute, especially during mesh refinement where there might be thousands of extremely small triangles. This is causing me issues with trying to enforce minimum angles for these triangles by placing these circumcenters.

**Comment by DanielVandH** [comment]
I did get a implementation going that seems to work, but there's some annoying changes I had to make in the code that I don't think will be worth making such a change for. So, with this and our previous discussion, I'll close this.
