### ISSUE TITLE
Tests error on IntervalArithmetic@0.22.6

### ISSUE THREAD

**Issue by DanielVandH** [lairez/ExactPredicates.jl#25]
As of IntervalArithmetic@0.22.6, the following errors (taken from the tests)

```julia
julia> a = (2.0, 0.0)
(2.0, 0.0)

julia> b = (1.0, 1.0)
(1.0, 1.0)

julia> c = (1.0, -1.0)
(1.0, -1.0)

julia> d = (nextfloat(0.0), 0.0)
(5.0e-324, 0.0)

julia> incircle(a, b, c, d)
ERROR: ArgumentError: `==` is only supported between thin intervals and numbers
Stacktrace:
 [1] ==
   @ C:\Users\User\.julia\packages\IntervalArithmetic\rX8mD\src\intervals\real_interface.jl:149 [inlined]
 [2] ==(x::IntervalArithmetic.Interval{Float64}, y::Int64)
   @ IntervalArithmetic C:\Users\User\.julia\packages\IntervalArithmetic\rX8mD\src\intervals\real_interface.jl:155
 [3] incircle_slow(p::Tuple{Float64, Float64}, q::Tuple{Float64, Float64}, r::Tuple{Float64, Float64}, a::Tuple{Float64, Float64})
   @ ExactPredicates C:\Users\User\.julia\dev\ExactPredicates.jl-1\src\Codegen.jl:340
 [4] incircle(p::Tuple{Float64, Float64}, q::Tuple{Float64, Float64}, r::Tuple{Float64, Float64}, a::Tuple{Float64, Float64})
   @ ExactPredicates C:\Users\User\.julia\dev\ExactPredicates.jl-1\src\Codegen.jl:470
 [5] top-level scope
   @ c:\Users\User\.julia\dev\ExactPredicates.jl-1\test\runtests.jl:57
```

No error on v0.22.5. I'm not sure I understand what the issue is looking at `incircle_slow` (or if this is actually an IntervalArithmetic issue rather than an ExactPredicates issue. maybe @OlivierHnt knows since they updated #24 previously?).

**Comment by lairez** [comment]
https://github.com/JuliaIntervals/IntervalArithmetic.jl/pull/613 introduced a breaking change, so things break...

**Comment by OlivierHnt** [comment]
That's the culprit. I can revert it, it should not have been breaking. I was being too presumptuous.

But I am not sure I understand this error

https://github.com/lairez/ExactPredicates.jl/blob/a9dce0334ee62104a14930fe206764bf802c23db/src/Codegen.jl#L340

seems ok to me, since `mag` returns a `Float64`,  not an interval.

**Comment by OlivierHnt** [comment]
Ah I see you just changed it, it was `$ivres == 0` before. Btw you could also have done `isthinzero($ivres)`.

**Comment by lairez** [comment]
No worries, it happens all the time
