### ISSUE TITLE
What does `defgeneric=nogeneric` do in `@genpredicate`?

### ISSUE THREAD

**Issue by DanielVandH** [lairez/ExactPredicates.jl#26]
I think this argument is only used in `closest` (where you give `nogeneric`), but I can't see what `defgeneric`  is doing in `@genpredicate` here or what it might be useful for:

https://github.com/lairez/ExactPredicates.jl/blob/a9dce0334ee62104a14930fe206764bf802c23db/src/Codegen.jl#L429-L438

I presume this option isn't intended to be public, but is there a good use for it?

**Comment by lairez** [comment]
If I remember well, this is because `closest` can be defined for point in the plane or in the space, so the macros do not define `closest` with generic argument to avoid conflicting implementations.

**Comment by DanielVandH** [comment]
Ah, that makes sense. Thanks :)
