### ISSUE TITLE
Outdated version in Julia's Pkg registry

### ISSUE THREAD

**Issue by mdmaas** [lairez/ExactPredicates.jl#3]
Hi! Great job on this package, I'm looking forward to use it!.

I was just checking the documentation, and it seems that the code in Julia's Pkg registry is quite outdated. This could be easily solve with Julia's [Registrator.jl](https://github.com/JuliaRegistries/Registrator.jl). I've never used it but apparently, if a project collaborator creates an issue and adds @JuliaRegistrator register as a comment, a bot will take care.

Regards!

**Comment by lairez** [comment]
Hi @mdmaas, thanks for your message, and sorry for late answer. As far as I can tell, Julia's registry is up to date (version 2.2.1). Con you provide more details?

**Comment by mdmaas** [comment]
Hi Pierre,

I'm not exactly sure what happened the last time.

I remember I got an error when running the examples of "working with other types of points" from the documentation, and I thought I had fixed it by downloading the last version from the Github repo.

I'll open a new issue because I'm getting the same error now, in all cases.
