### ISSUE TITLE
Error working with other types of points

### ISSUE THREAD

**Issue by mdmaas** [lairez/ExactPredicates.jl#4]
I run some examples from the documentation, like those under "working with other type of points":

```
using ExactPredicates
struct Point
    x :: Float64
    y :: Float64
end

Tuple(p :: Point) = (p.x, p.y)
incircle(Point(0.0, 0.0), Point(1.0, 0.0), Point(0.0, 1.0), Point(.5, .5))
```
I get an error that starts with:
```
MethodError: no method matching length(::Point)
(...)
```

**Comment by mdmaas** [comment]
The example using complex numbers also doesn't seem to work:
```
StackOverflowError:
Stacktrace:
 [1] incircle(p::Core.Tuple{Float64}, q::Core.Tuple{Float64}, r::Core.Tuple{Float64, Float64}, a::Core.Tuple{Float64, Float64}) (repeats 79984 times)
   @ ExactPredicates ~/.julia/dev/ExactPredicates/src/Codegen.jl:422
```
and the one with StaticArrays does work as expected.

**Comment by lairez** [comment]
It is actually two documentation errors : it should be `Core.Tuple` and `ExactPredicates.coord`. Otherwise, we just define a new method `Tuple` or `coord` that is not found by the package. I am fixing it. Thanks for reporting!
