### ISSUE TITLE
StackOverflowError for StaticArrays example

### ISSUE THREAD

**Issue by DanielVandH** [lairez/ExactPredicates.jl#5]
The provided code in the README for working with static arrays returns a StackOverflowError:

```
using StaticArrays
incircle(SVector(0.0, 0.0), SVector(1.0, 0.0), SVector(0.0, 1.0), SVector(.5, .5))
```
```
ERROR: StackOverflowError:
Stacktrace:
 [1] incircle(a::SVector{2, ComplexF64}, b::SVector{2, ComplexF64}, c::SVector{2, ComplexF64}, p::SVector{2, ComplexF64}) (repeats 79984 times)
   @ ExactPredicates C:\Users\licer\.julia\packages\ExactPredicates\YJYhc\src\ExactPredicates.jl:141
```
This seems to happen when the method falls back to the following:
```
julia> @which incircle(SVector(0.0, 0.0), SVector(1.0, 0.0), SVector(0.0, 1.0), SVector(.5, .5))
incircle(a, b, c, p) in ExactPredicates at C:\Users\licer\.julia\packages\ExactPredicates\YJYhc\src\ExactPredicates.jl:141
```
In another instance I had it fall back to a Codegen file and it gave the correct answer:
```
julia> incircle(SVector(0.0, 0.0), SVector(1.0, 0.0), SVector(0.0, 1.0), SVector(.5, .5))
1

julia> @which incircle(SVector(0.0, 0.0), SVector(1.0, 0.0), SVector(0.0, 1.0), SVector(.5, .5))
incircle(p, q, r, a) in ExactPredicates at C:\Users\licer\.julia\packages\ExactPredicates\niW2X\src\Codegen.jl:420
```

**Comment by lairez** [comment]
Thanks for reporting! The code works fine on my computer. Do you have the latest version? (For example, ExactPredicates.jl does not have a line 141 in the current version.)

**Comment by DanielVandH** [comment]
Ah I see. I wasn't aware that `Pkg.add` had added the oldest version, even after removing and reinstalling the package. Doing `] add ExactPredicates@2.2.1` and running the test again shows no issues. Thanks.
